on:
  push:
    branches:
      - '3/[a-z]+'
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap_without_cache.yaml@v2

  publish:
    name: Publish Snap
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}
      - id: get-snap-name
        run: echo "SNAP_FILE=$(ls *.snap)" >> $GITHUB_OUTPUT
      - name: Publish snap
        id: publish
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.get-snap-name.outputs.SNAP_FILE }}
          release: ${{ github.ref_name }}
      - name: Upload snapcraft logs
        if: ${{ failure() && steps.publish.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: snapcraft-release-logs
          path: ~/.local/state/snapcraft/log/
          if-no-files-found: error